version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:latest' # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello cruel world" # run the `echo` command
      - run: mvn test -f hhan-endpoints/HelloWorldFunction/pom.xml
      - store_test_results:
          path: hhan-endpoints/HelloWorldFunction/target/surefire-reports
      - store_artifacts:
          path:  hhan-endpoints/HelloWorldFunction/target/my-reports


