name: Maven Test with Codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn test --file ./HelloWorldFunction/pom.xml

    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

    - name: codacy-coverage-reporter
        runs-on: ubuntu-latest
        name: codacy-coverage-reporter
        steps:
          - uses: actions/checkout@master
          - name: Run codacy-coverage-reporter
            uses: codacy/codacy-coverage-reporter-action@master
            with:
              project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
              coverage-reports: cobertura.xml

      - name:  code_climate_coverage_reporter
        - uses: paambaati/codeclimate-action@v2.5.7
            env:
              CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
            with:
              coverage-reports: cobertura.xml